<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SvfPlayer.dll" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SvfPlayer.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartIct.Interfaces\Interfaces.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ProMik.SvfPlayer">
      <HintPath>..\..\External DLLs\ProMik.SvfPlayer.dll</HintPath>
    </Reference>
    <Reference Include="BSDLProcessor.Interfaces">
      <HintPath>..\..\External DLLs\BSDLProcessor.Interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
