<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Platforms>AnyCPU;x64;x86</Platforms>
	<VersionPrefix>1.0.1</VersionPrefix>
    <PackageId>ProMik.SmartIct.Svf.SvfFileCreation</PackageId>
    <PackageProjectUrl>https://gitlab.promik.local/flash_task/host/smart_ict_analyser/-/tree/master/SmartIctTool/NetStandard/SvfHelper</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SvfPlayer.dll" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SvfPlayer.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ProMik.BSDL.Interfaces" Version="1.0.16-beta" />
    <PackageReference Include="ProMik.Svf.Contracts" Version="1.0.0" />
    <PackageReference Include="ProMik.SvfPlayer" Version="1.0.20-beta" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartIct.Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\ManifestHandling\ManifestHandling.csproj" />
    <ProjectReference Include="..\SvfInterfaces\SvfInterfaces\SvfInterfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="SvfPlayer_x86.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
