<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
	<VersionPrefix>1.0.1</VersionPrefix>
    <PackageId>ProMik.SmartIct.Services.ReportCreator</PackageId>
    <PackageProjectUrl>https://gitlab.promik.local/flash_task/host/smart_ict_analyser/-/tree/master/SmartIctTool/NetStandard/ReportCreator</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="27.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartIct.Interfaces\Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="TextRessources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TextRessources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="TextRessources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TextRessources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
