<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartIct.Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\GrpcApi\GrpcApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PCB-Investigator">
      <HintPath>SolutionItems\PCB-Investigator.exe</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LangRessource.Designer.cs">
      <DependentUpon>LangRessource.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="LangRessource.resx">
      <LastGenOutput>LangRessource.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="SolutionItems\PCB-Investigator.exe">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
