<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
    <Platforms>AnyCPU;x64</Platforms>
    <NeutralLanguage>en-150</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="proto\PcbInvestigatorService.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.15.6" />
    <PackageReference Include="Grpc" Version="2.36.4" />
    <PackageReference Include="Grpc.Core" Version="2.36.4" />
    <PackageReference Include="Grpc.Core.Api" Version="2.36.4" />
    <PackageReference Include="Grpc.Tools" Version="2.36.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartIct.Interfaces\Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="proto\PcbInvestigatorService.proto" GrpcServices="Server">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Protobuf>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PCB-Investigator">
      <HintPath>..\..\Solution Items\PCB-Investigator.exe</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
    <AdditionalFiles Include="..\..\stylecop.json" Link="Properties\stylecop.json" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.333">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="LangRessource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LangRessource.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="LangRessource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>LangRessource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
