//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcbInvestigatorApiV10 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRessource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRessource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PcbInvestigatorApiV10.LangRessource", typeof(LangRessource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress the zipped content: {0}ms.
        /// </summary>
        internal static string DecompressZippedContent {
            get {
                return ResourceManager.GetString("DecompressZippedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error by receiving empty zip folder data!.
        /// </summary>
        internal static string ErrorByReceivingEmptyZipFolder {
            get {
                return ResourceManager.GetString("ErrorByReceivingEmptyZipFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting parsed objects by folder!.
        /// </summary>
        internal static string ErrorGettingParsedObjectsByFolder {
            get {
                return ResourceManager.GetString("ErrorGettingParsedObjectsByFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse all objects in serializable: {0}ms.
        /// </summary>
        internal static string ParseAllObjectsIntoSerializable {
            get {
                return ResourceManager.GetString("ParseAllObjectsIntoSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read out by PCB Investigator: {0}ms.
        /// </summary>
        internal static string ReadOutByPcbInvestigator {
            get {
                return ResourceManager.GetString("ReadOutByPcbInvestigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used project file with other password!.
        /// </summary>
        internal static string UsedOtherPassword {
            get {
                return ResourceManager.GetString("UsedOtherPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
