<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Ui</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
    <NeutralLanguage>en-150</NeutralLanguage>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Ressources\start.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="MaterialDesignThemes" Version="3.2.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="3.1.0" />
    <PackageReference Include="Prism.DryIoc" Version="8.0.0.1909" />
    <PackageReference Include="ProMik.BSDL.Interfaces" Version="1.0.3-beta" />
    <PackageReference Include="ProMik.BSDL.Processor" Version="1.0.3-beta" />
    <PackageReference Include="ProMik.Core" Version="1.0.20-beta" />
    <PackageReference Include="ProMik.Core.Interfaces" Version="1.0.20-beta" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ui.Core\Ui.Core.csproj" />
    <ProjectReference Include="..\Modules\Ui.Modules.ModuleName\Ui.Modules.ModuleName.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
    <AdditionalFiles Include="..\..\stylecop.json" Link="Properties\stylecop.json" />
    <Resource Include="Ressources\start.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.333">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>