<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Ui</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.0.1" />
    <PackageReference Include="MaterialDesignThemes" Version="3.2.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="3.1.0" />
    <PackageReference Include="Prism.DryIoc" Version="8.0.0.1909" />
    <PackageReference Include="ProMik.Services" Version="0.0.1" />
    <PackageReference Include="ProMik.Services.Interfaces" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Tests\TestCoverage\TestCoverage.csproj" />
    <ProjectReference Include="..\Ui.Core\Ui.Core.csproj" />
    <ProjectReference Include="..\Modules\Ui.Modules.ModuleName\Ui.Modules.ModuleName.csproj" />
    <ProjectReference Include="..\Services\Ui.Services\Ui.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
    <AdditionalFiles Include="..\..\stylecop.json" Link="Properties\stylecop.json" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="TextResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TextResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="TextResource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TextResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>