//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ui.Modules.ModuleName {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextRessources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ui.Modules.ModuleName.TextRessources", typeof(TextRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the cable compensation for JTAG device: ähnelt.
        /// </summary>
        internal static string CableCompensation {
            get {
                return ResourceManager.GetString("CableCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export into JSON file: {0}ms ähnelt.
        /// </summary>
        internal static string ExportIntoJsonFile {
            get {
                return ResourceManager.GetString("ExportIntoJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export object data ähnelt.
        /// </summary>
        internal static string ExportObjectData {
            get {
                return ResourceManager.GetString("ExportObjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export settings file&quot; ähnelt.
        /// </summary>
        internal static string ExportSettingsFile {
            get {
                return ResourceManager.GetString("ExportSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the frequency to be used in Hz for JTAG device: ähnelt.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type in the frequency in Hz to use and the cable compensation (a;b) for the JTAG device: ähnelt.
        /// </summary>
        internal static string FrequencyAndCableCompensation {
            get {
                return ResourceManager.GetString("FrequencyAndCableCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import object data from file ähnelt.
        /// </summary>
        internal static string ImportDataFromFile {
            get {
                return ResourceManager.GetString("ImportDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import settings file ähnelt.
        /// </summary>
        internal static string ImportSettingsFile {
            get {
                return ResourceManager.GetString("ImportSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die json files (*.json)|*.json|All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string JsonFilter {
            get {
                return ResourceManager.GetString("JsonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF files (*.pdf)|*.pdf|All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string PdfFilter {
            get {
                return ResourceManager.GetString("PdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select or specify the PDF file to be saved at ähnelt.
        /// </summary>
        internal static string PdfSaveFile {
            get {
                return ResourceManager.GetString("PdfSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export PIN connection information into local file ähnelt.
        /// </summary>
        internal static string PinExportTitle {
            get {
                return ResourceManager.GetString("PinExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select BOM file ähnelt.
        /// </summary>
        internal static string SelectBomFile {
            get {
                return ResourceManager.GetString("SelectBomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select BSDL file for JTAG device ähnelt.
        /// </summary>
        internal static string SelectBsdlFile {
            get {
                return ResourceManager.GetString("SelectBsdlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the project file for opening ähnelt.
        /// </summary>
        internal static string SelectProjectFileForOpening {
            get {
                return ResourceManager.GetString("SelectProjectFileForOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select location for saving the project file ähnelt.
        /// </summary>
        internal static string SelectProjectFileToSave {
            get {
                return ResourceManager.GetString("SelectProjectFileToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select folder to save the SVF files at ähnelt.
        /// </summary>
        internal static string SelectSvfFolder {
            get {
                return ResourceManager.GetString("SelectSvfFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the SVF folder to be played ähnelt.
        /// </summary>
        internal static string SelectSvfFolderForPlay {
            get {
                return ResourceManager.GetString("SelectSvfFolderForPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the ODB project path ähnelt.
        /// </summary>
        internal static string SelectTheOdbProjectPath {
            get {
                return ResourceManager.GetString("SelectTheOdbProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select VSF file(s) to be played with the programmer ähnelt.
        /// </summary>
        internal static string SelectVsfFile {
            get {
                return ResourceManager.GetString("SelectVsfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die database files (*.db)|*.db|All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string SettingsFilter {
            get {
                return ResourceManager.GetString("SettingsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the output logfolder ähnelt.
        /// </summary>
        internal static string SvfLogPath {
            get {
                return ResourceManager.GetString("SvfLogPath", resourceCulture);
            }
        }
    }
}
